# Generated by Django 3.1.7 on 2021-02-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210224_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='d',
            new_name='choose_date',
        ),
    ]
