# Generated by Django 3.1.7 on 2021-02-26 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210224_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='dardate',
            field=models.DateField(default=datetime.date(2021, 2, 26)),
        ),
    ]
